name: Cleanup Artifacts

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "0 0 * * 1"
    # watch:
    #     types: [started]

permissions: write-all

env:
    TOKEN: ${{ github.token }}

jobs:
    Cleanup_Artifacts:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
          - run: echo hi
