name: Cleanup Workflows Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  watch:
    types: [started]

permissions: write-all

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  Cleanup_Workflows_Runs:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: This repo itself
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ env.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 60
          keep_minimum_runs: 6

      - name: Rclone-Auto-Refresh-Token
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ env.TOKEN }}
          repository: KevinNitroG/Rclone-Auto-Refresh-Token
          retain_days: 15
          keep_minimum_runs: 6

      # - name: Rclone-Auto-Refresh-Token - self-hosted
      #   uses: Mattraks/delete-workflow-runs@main
      #   with:
      #     token: ${{ env.TOKEN }}
      #     repository: Kev-Self-Hosted/Rclone-Auto-Refresh-Token
      #     retain_days: 15
      #     keep_minimum_runs: 6

      # - name: MSO_E5_Dev_AutoRenew_GA
      #   uses: Mattraks/delete-workflow-runs@main
      #   with:
      #       token: ${{ env.TOKEN }}
      #       repository: KevinNitroG/MSO_E5_Dev_AutoRenew_GA
      #       retain_days: 7
      #       keep_minimum_runs: 6

      - name: Entertainment
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ env.TOKEN }}
          repository: KevinNitroG/Entertainment
          retain_days: 15
          keep_minimum_runs: 6

      - name: ReVanced-auto-build
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ env.TOKEN }}
          repository: KevinNitroG/Entertainment
          retain_days: 15
          keep_minimum_runs: 6

      # - name: MSO_E5_Dev_AutoRenew_GA - self-hosted
      #   uses: Mattraks/delete-workflow-runs@main
      #   with:
      #     token: ${{ env.TOKEN }}
      #     repository: Kev-Self-Hosted/I-faive-rinew
      #     retain_days: 7
      #     keep_minimum_runs: 6

      - name: MSO_E5_Dev_AutoRenew_GA
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ env.TOKEN }}
          repository: KevinNitroG/E5-Restore
          retain_days: 7
          keep_minimum_runs: 6
